"""Enhanced Visual Music Graph workspace — embedded interactive scatter plot."""
from __future__ import annotations

import json
import logging
import numpy as np
from pathlib import Path
from typing import Optional, Dict, List

from gui.compat import QtCore, QtGui, QtWidgets, Signal, Slot
from gui.workspaces.base import WorkspaceBase

logger = logging.getLogger(__name__)

try:
    from gui.widgets.interactive_scatter_plot import InteractiveScatterPlot
    from gui.widgets.cluster_legend import ClusterLegendWidget
    from gui.widgets.track_details_panel import TrackDetailsPanel
except ImportError:
    InteractiveScatterPlot = None
    ClusterLegendWidget = None
    TrackDetailsPanel = None


class GraphWorkspace(WorkspaceBase):
    """Embedded interactive cluster scatter-plot visualization."""

    def __init__(self, library_path: str = "", parent: QtWidgets.QWidget | None = None) -> None:
        super().__init__(library_path, parent)

        self._cluster_data: Dict | None = None
        self._scatter: InteractiveScatterPlot | None = None
        self._legend: ClusterLegendWidget | None = None
        self._details: TrackDetailsPanel | None = None

        self._build_ui()
        self._library_changed(library_path)

    def _build_ui(self) -> None:
        """Build the UI."""
        cl = self.content_layout

        # Title
        cl.addWidget(self._make_section_title("Visual Music Graph"))
        cl.addWidget(self._make_subtitle(
            "Explore your clustered library as an interactive scatter plot. "
            "Hover points to see metadata, select clusters to export playlists. "
            "Run Clustered Playlists first to generate cluster data."
        ))

        # Status and controls
        control_card = self._make_card()
        control_layout = QtWidgets.QHBoxLayout(control_card)

        self._status_lbl = QtWidgets.QLabel("Loading...")
        self._status_lbl.setStyleSheet("color: #666; font-size: 11px;")
        control_layout.addWidget(self._status_lbl)

        control_layout.addStretch(1)

        refresh_btn = QtWidgets.QPushButton("↺ Refresh")
        refresh_btn.clicked.connect(self._on_refresh)
        control_layout.addWidget(refresh_btn)

        cl.addWidget(control_card)

        # Main graph area (only if PyQtGraph available)
        if InteractiveScatterPlot is not None:
            self._build_graph_ui(cl)
        else:
            self._build_fallback_ui(cl)

        cl.addStretch(1)

    def _build_graph_ui(self, parent_layout: QtWidgets.QVBoxLayout) -> None:
        """Build the interactive graph UI."""
        # Main layout: scatter plot + sidebar
        main_layout = QtWidgets.QHBoxLayout()

        # Left: scatter plot (main area)
        self._scatter = InteractiveScatterPlot()
        self._scatter.point_clicked.connect(self._on_point_clicked)
        self._scatter.hover_changed.connect(self._on_hover)
        main_layout.addWidget(self._scatter, 3)

        # Right sidebar: legend + details
        sidebar_layout = QtWidgets.QVBoxLayout()
        sidebar_layout.setSpacing(8)

        # Cluster legend
        self._legend = ClusterLegendWidget()
        self._legend.cluster_toggled.connect(self._on_cluster_toggled)
        self._legend.cluster_selected.connect(self._on_cluster_selected)
        sidebar_layout.addWidget(self._legend, 1)

        # Track details
        self._details = TrackDetailsPanel()
        sidebar_layout.addWidget(self._details, 1)

        main_layout.addLayout(sidebar_layout, 1)
        parent_layout.addLayout(main_layout, 1)

        # Bottom: selection actions
        action_layout = QtWidgets.QHBoxLayout()
        action_layout.setSpacing(6)

        export_btn = QtWidgets.QPushButton("📄 Export Selection")
        export_btn.clicked.connect(self._on_export_selection)
        action_layout.addWidget(export_btn)

        playlist_btn = QtWidgets.QPushButton("🎵 Create Playlist from Selection")
        playlist_btn.clicked.connect(self._on_create_playlist)
        action_layout.addWidget(playlist_btn)

        fit_btn = QtWidgets.QPushButton("⊡ Fit View")
        fit_btn.clicked.connect(self._on_fit_view)
        action_layout.addWidget(fit_btn)

        action_layout.addStretch(1)
        parent_layout.addLayout(action_layout)

    def _build_fallback_ui(self, parent_layout: QtWidgets.QVBoxLayout) -> None:
        """Build fallback UI when PyQtGraph not available."""
        warning_card = self._make_card()
        warning_layout = QtWidgets.QVBoxLayout(warning_card)

        warning_label = QtWidgets.QLabel(
            "⚠️ PyQtGraph not installed\n\n"
            "The interactive scatter plot requires PyQtGraph.\n"
            "However, cluster data is still being generated by the\n"
            "Clustered Playlists workspace.\n\n"
            "To enable the interactive graph:\n"
            "   1. Install PyQtGraph: pip install pyqtgraph\n"
            "   2. Restart the application\n\n"
            "You can still:\n"
            "   • Export cluster data as CSV or M3U playlists\n"
            "   • View cluster quality reports\n"
            "   • Access cluster info from the Clustered Playlists workspace"
        )
        warning_label.setWordWrap(True)
        warning_label.setStyleSheet("color: #f59e0b; font-size: 12px;")
        warning_layout.addWidget(warning_label)

        # Add a button to copy the install command
        button_layout = QtWidgets.QHBoxLayout()
        copy_btn = QtWidgets.QPushButton("📋 Copy Install Command")
        copy_btn.clicked.connect(self._copy_install_command)
        button_layout.addWidget(copy_btn)
        button_layout.addStretch()
        warning_layout.addLayout(button_layout)

        parent_layout.addWidget(warning_card)

    def _copy_install_command(self) -> None:
        """Copy installation command to clipboard."""
        clipboard = QtWidgets.QApplication.clipboard()
        clipboard.setText("pip install pyqtgraph")
        QtWidgets.QMessageBox.information(
            self,
            "Command Copied",
            "Installation command copied to clipboard:\npip install pyqtgraph"
        )

    def _library_changed(self, path: str) -> None:
        """Called when library path changes."""
        self._library_path = path
        self._load_cluster_data()

    def _load_cluster_data(self) -> None:
        """Load cluster data from library."""
        if not self._library_path or self._scatter is None:
            self._status_lbl.setText("No library selected")
            return

        lib_path = Path(self._library_path)

        # Validate library path exists and is accessible
        if not lib_path.exists():
            self._status_lbl.setText("Library path does not exist")
            self._status_lbl.setStyleSheet("color: #ef4444;")
            logger.error(f"Library path not found: {lib_path}")
            return

        if not lib_path.is_dir():
            self._status_lbl.setText("Library path is not a directory")
            self._status_lbl.setStyleSheet("color: #ef4444;")
            logger.error(f"Library path is not a directory: {lib_path}")
            return

        # Check read permissions
        try:
            list(lib_path.iterdir())
        except PermissionError:
            self._status_lbl.setText("No permission to read library folder")
            self._status_lbl.setStyleSheet("color: #ef4444;")
            logger.error(f"Permission denied reading library: {lib_path}")
            return
        except OSError as e:
            self._status_lbl.setText(f"Cannot access library: {e}")
            self._status_lbl.setStyleSheet("color: #ef4444;")
            logger.error(f"Error accessing library: {e}")
            return

        # Look for cluster data files
        cluster_info_file = lib_path / "Docs" / "cluster_info.json"
        if not cluster_info_file.exists():
            cluster_info_file = lib_path / "cluster_info.json"

        if not cluster_info_file.exists():
            self._status_lbl.setText("No cluster data found — run Clustered Playlists first")
            self._scatter.scatter.clear()
            if self._legend:
                self._legend.set_clusters(np.array([]), {})
            return

        try:
            # Load cluster info with error handling
            try:
                with open(cluster_info_file) as f:
                    cluster_info = json.load(f)
            except json.JSONDecodeError as e:
                self._status_lbl.setText(f"Corrupted cluster data file: {e}")
                self._status_lbl.setStyleSheet("color: #ef4444;")
                logger.error(f"Failed to parse JSON from {cluster_info_file}: {e}")
                return
            except OSError as e:
                self._status_lbl.setText(f"Cannot read cluster file: {e}")
                self._status_lbl.setStyleSheet("color: #ef4444;")
                logger.error(f"Failed to read {cluster_info_file}: {e}")
                return

            # Validate required keys exist
            required_keys = ["X", "labels", "tracks"]
            missing_keys = [k for k in required_keys if k not in cluster_info]
            if missing_keys:
                self._status_lbl.setText(f"Invalid cluster data: missing {', '.join(missing_keys)}")
                self._status_lbl.setStyleSheet("color: #ef4444;")
                logger.error(f"Missing required keys in cluster data: {missing_keys}")
                return

            # Extract data with type validation
            try:
                X = np.array(cluster_info["X"], dtype=np.float32)
                labels = np.array(cluster_info["labels"], dtype=np.int32)
                tracks = cluster_info.get("tracks", [])
                cluster_metadata = cluster_info.get("cluster_info", {})
            except (TypeError, ValueError) as e:
                self._status_lbl.setText(f"Invalid cluster data types: {e}")
                self._status_lbl.setStyleSheet("color: #ef4444;")
                logger.error(f"Failed to parse cluster data types: {e}")
                return

            # Validate array lengths match
            if len(X) != len(labels) or len(labels) != len(tracks):
                self._status_lbl.setText(
                    f"Mismatched cluster data lengths: X={len(X)}, labels={len(labels)}, tracks={len(tracks)}"
                )
                self._status_lbl.setStyleSheet("color: #ef4444;")
                logger.error(f"Array length mismatch in cluster data")
                return

            if len(X) == 0:
                self._status_lbl.setText("No cluster data available")
                return

            # Check if X was downsampled for visualization
            x_downsampled = cluster_info.get("X_downsampled", False)
            x_total = cluster_info.get("X_total_points", len(X))
            if x_downsampled and x_total > 0:
                logger.info(f"Cluster data: X downsampled from {x_total} to {len(X)} points for visualization")

            # Create metadata dict for each point
            metadata = []
            for track_path in tracks:
                track_name = Path(track_path).name
                metadata.append({
                    "path": track_path,
                    "title": track_name,
                    "artist": "Unknown",
                    "album": "Unknown",
                    "genres": [],
                    "bpm": 0,
                    "duration": 0,
                })

            # Generate colors by cluster
            unique_clusters = np.unique(labels)
            colors = []
            for label in labels:
                # Simple color generation based on cluster
                hue = (int(label) % len(unique_clusters)) / max(len(unique_clusters), 1)
                color = (
                    int(100 + 155 * (1 - hue)),  # R
                    int(100 + 155 * hue),        # G
                    int(200),                     # B
                )
                colors.append(color)

            colors = np.array(colors)

            # Set scatter plot data
            self._scatter.set_data(
                X=X,
                clusters=labels,
                labels=tracks,
                metadata=metadata,
            )

            # Set legend
            if self._legend:
                self._legend.set_clusters(labels, cluster_metadata, colors)

            # Update status
            n_clusters = len(unique_clusters)
            n_tracks = len(labels)
            self._status_lbl.setText(
                f"✓ Loaded: {n_clusters} cluster(s), {n_tracks} track(s)"
            )
            self._status_lbl.setStyleSheet("color: #22c55e;")

            self._cluster_data = {
                "X": X,
                "labels": labels,
                "tracks": tracks,
                "metadata": metadata,
                "cluster_info": cluster_metadata,
            }

        except Exception as e:
            self._status_lbl.setText(f"Error loading cluster data: {e}")
            self._status_lbl.setStyleSheet("color: #ef4444;")
            self._log(f"Error loading cluster data: {e}", "error")

    @Slot()
    def _on_refresh(self) -> None:
        """Refresh cluster data."""
        self._load_cluster_data()
        self._log("Refreshed cluster data", "info")

    @Slot(int)
    def _on_point_clicked(self, index: int) -> None:
        """Handle point click."""
        if self._cluster_data is None or index < 0:
            return

        # Validate index is within all arrays
        metadata_len = len(self._cluster_data.get("metadata", []))
        tracks_len = len(self._cluster_data.get("tracks", []))

        if index >= metadata_len or index >= tracks_len:
            logger.warning(f"Point index {index} out of bounds (metadata={metadata_len}, tracks={tracks_len})")
            return

        metadata = self._cluster_data["metadata"][index]
        if self._details:
            self._details.set_track(metadata)

        self._log(f"Selected: {metadata.get('title', 'Unknown')}", "info")

    @Slot(int)
    def _on_hover(self, index: int) -> None:
        """Handle point hover."""
        if index < 0 or self._cluster_data is None:
            if self._details:
                self._details._clear_display()
            return

        # Validate index is within all arrays
        metadata_len = len(self._cluster_data.get("metadata", []))
        tracks_len = len(self._cluster_data.get("tracks", []))

        if index >= metadata_len or index >= tracks_len:
            if self._details:
                self._details._clear_display()
            return

        metadata = self._cluster_data["metadata"][index]
        if self._details:
            self._details.set_track(metadata)

    @Slot(int, bool)
    def _on_cluster_toggled(self, cluster_id: int, visible: bool) -> None:
        """Handle cluster visibility toggle."""
        if self._scatter:
            self._scatter.set_cluster_visible(cluster_id, visible)
        self._log(f"Cluster {cluster_id}: {'shown' if visible else 'hidden'}", "info")

    @Slot(int)
    def _on_cluster_selected(self, cluster_id: int) -> None:
        """Handle cluster selection."""
        if self._scatter:
            self._scatter.highlight_cluster(cluster_id)
        self._log(f"Highlighted cluster {cluster_id}", "info")

    @Slot()
    def _on_fit_view(self) -> None:
        """Fit view to show all points."""
        if self._scatter:
            self._scatter.fit_view()

    @Slot()
    def _on_export_selection(self) -> None:
        """Export selected points as CSV."""
        if self._scatter is None or self._cluster_data is None:
            QtWidgets.QMessageBox.warning(self, "No Selection", "Please select points first")
            return

        selected_paths = self._scatter.export_selection_paths()
        if not selected_paths:
            QtWidgets.QMessageBox.warning(self, "No Selection", "Please select points first")
            return

        # Show save dialog
        file_path, _ = QtWidgets.QFileDialog.getSaveFileName(
            self,
            "Export Selection",
            f"{self._library_path}/selection.csv",
            "CSV Files (*.csv)"
        )

        if not file_path:
            return

        # Write CSV with atomic write (temp file then move)
        try:
            import tempfile
            import csv
            from pathlib import Path as PathlibPath

            # Create temp file in same directory for atomic write
            temp_fd, temp_path = tempfile.mkstemp(dir=PathlibPath(file_path).parent, text=True)

            try:
                with open(temp_fd, 'w', newline='') as f:
                    writer = csv.writer(f)
                    writer.writerow(["path"])
                    for path in selected_paths:
                        writer.writerow([path])

                # Atomic rename
                PathlibPath(temp_path).replace(file_path)

                self._log(f"Exported {len(selected_paths)} track(s) to {file_path}", "ok")
                QtWidgets.QMessageBox.information(
                    self, "Export Complete", f"Exported {len(selected_paths)} track(s)"
                )
            except Exception as write_err:
                # Clean up temp file
                PathlibPath(temp_path).unlink(missing_ok=True)
                raise write_err

        except OSError as e:
            self._log(f"Export failed (disk error): {e}", "error")
            QtWidgets.QMessageBox.critical(self, "Export Failed", f"Disk error: {e}")
        except Exception as e:
            self._log(f"Export failed: {e}", "error")
            logger.exception("Export selection failed")
            QtWidgets.QMessageBox.critical(self, "Export Failed", str(e))

    @Slot()
    def _on_create_playlist(self) -> None:
        """Create M3U playlist from selection."""
        if self._scatter is None or self._cluster_data is None:
            QtWidgets.QMessageBox.warning(self, "No Selection", "Please select points first")
            return

        selected_paths = self._scatter.export_selection_paths()
        if not selected_paths:
            QtWidgets.QMessageBox.warning(self, "No Selection", "Please select points first")
            return

        # Ask for playlist name
        name, ok = QtWidgets.QInputDialog.getText(
            self,
            "Create Playlist",
            "Playlist name:",
            text="Selected Tracks"
        )

        if not ok or not name:
            return

        # Write M3U with proper error handling
        try:
            import tempfile

            playlists_dir = Path(self._library_path) / "Playlists"
            try:
                playlists_dir.mkdir(exist_ok=True)
            except OSError as e:
                self._log(f"Playlist creation failed (cannot create folder): {e}", "error")
                QtWidgets.QMessageBox.critical(self, "Playlist Creation Failed", f"Cannot create Playlists folder: {e}")
                return

            playlist_path = playlists_dir / f"{name}.m3u"

            # Write to temp file first
            temp_fd, temp_path = tempfile.mkstemp(dir=playlists_dir, text=True, suffix='.m3u')

            try:
                with open(temp_fd, 'w') as f:
                    f.write("#EXTM3U\n")
                    for path in selected_paths:
                        f.write(f"{path}\n")

                # Atomic rename
                Path(temp_path).replace(playlist_path)

                self._log(f"Created playlist: {playlist_path}", "ok")
                QtWidgets.QMessageBox.information(
                    self, "Playlist Created",
                    f"Created playlist with {len(selected_paths)} track(s)"
                )
            except Exception as write_err:
                # Clean up temp file
                Path(temp_path).unlink(missing_ok=True)
                raise write_err

        except OSError as e:
            self._log(f"Playlist creation failed (disk error): {e}", "error")
            QtWidgets.QMessageBox.critical(self, "Playlist Creation Failed", f"Disk error: {e}")
        except Exception as e:
            self._log(f"Playlist creation failed: {e}", "error")
            logger.exception("Playlist creation failed")
            QtWidgets.QMessageBox.critical(self, "Playlist Creation Failed", str(e))
