"""Visual Music Graph workspace — interactive scatter plot for clusters."""
from __future__ import annotations

import webbrowser
from pathlib import Path

from gui.compat import QtCore, QtGui, QtWidgets, Signal, Slot
from gui.workspaces.base import WorkspaceBase


class GraphWorkspace(WorkspaceBase):
    """Embed or launch the interactive cluster scatter-plot visualisation."""

    def __init__(self, library_path: str = "", parent: QtWidgets.QWidget | None = None) -> None:
        super().__init__(library_path, parent)
        self._build_ui()

    def _build_ui(self) -> None:
        cl = self.content_layout

        cl.addWidget(self._make_section_title("Visual Music Graph"))
        cl.addWidget(self._make_subtitle(
            "Explore your clustered library as an interactive scatter plot. "
            "Each point is a track; colour represents its cluster. "
            "Hover to see metadata; click to preview. "
            "Run Clustered Playlists first to generate cluster data."
        ))

        # ── Launch card ────────────────────────────────────────────────────
        launch_card = self._make_card()
        launch_layout = QtWidgets.QVBoxLayout(launch_card)
        launch_layout.setContentsMargins(16, 16, 16, 16)
        launch_layout.setSpacing(10)

        launch_layout.addWidget(QtWidgets.QLabel("Launch Graph"))

        info = QtWidgets.QLabel(
            "The Visual Music Graph opens in a separate Qt window with full pan/zoom support. "
            "It requires cluster data generated by the Clustered Playlists tool."
        )
        info.setWordWrap(True)
        info.setStyleSheet("color: #64748b; font-size: 12px;")
        launch_layout.addWidget(info)

        btn_row = QtWidgets.QHBoxLayout()
        self._open_graph_btn = self._make_primary_button("🌐  Open Visual Graph Window")
        self._open_graph_btn.clicked.connect(self._on_open_graph)
        self._open_html_btn = QtWidgets.QPushButton("🖥  Open as HTML (browser)")
        self._open_html_btn.clicked.connect(self._on_open_html)
        btn_row.addWidget(self._open_graph_btn)
        btn_row.addWidget(self._open_html_btn)
        btn_row.addStretch(1)
        launch_layout.addLayout(btn_row)

        self._status_lbl = QtWidgets.QLabel("")
        self._status_lbl.setStyleSheet("color: #64748b; font-size: 12px;")
        launch_layout.addWidget(self._status_lbl)
        cl.addWidget(launch_card)

        # ── Cluster data summary ───────────────────────────────────────────
        self._data_card = self._make_card()
        data_layout = QtWidgets.QVBoxLayout(self._data_card)
        data_layout.setContentsMargins(16, 16, 16, 16)
        data_layout.addWidget(QtWidgets.QLabel("Cluster Data Status"))

        self._data_status = QtWidgets.QLabel("No cluster data found — run Clustered Playlists first.")
        self._data_status.setStyleSheet("color: #f59e0b;")
        self._data_status.setWordWrap(True)
        data_layout.addWidget(self._data_status)

        self._refresh_btn = QtWidgets.QPushButton("↺  Refresh")
        self._refresh_btn.clicked.connect(self._check_data)
        data_layout.addWidget(self._refresh_btn)
        cl.addWidget(self._data_card)

        cl.addStretch(1)

        # Initial data check
        self._check_data()

    # ── Slots ─────────────────────────────────────────────────────────────

    @Slot()
    def _on_open_graph(self) -> None:
        QtWidgets.QMessageBox.information(
            self,
            "Visual Graph",
            "The Visual Music Graph requires cluster data generated by the "
            "Clustered Playlists tool.\n\n"
            "Run a clustering session from the Clustered Playlists workspace "
            "first — the graph window will open automatically once cluster "
            "data is available.",
        )

    @Slot()
    def _on_open_html(self) -> None:
        if not self._library_path:
            return
        candidates = [
            Path(self._library_path) / "Docs" / "cluster_graph.html",
            Path(self._library_path) / "cluster_graph.html",
        ]
        for c in candidates:
            if c.exists():
                webbrowser.open(f"file://{c}")
                return
        self._status_lbl.setText("No cluster_graph.html found. Run clustering first.")

    @Slot()
    def _check_data(self) -> None:
        if not self._library_path:
            self._data_status.setText("No library selected.")
            return
        log_files = list(Path(self._library_path).glob("*_log.txt"))
        if log_files:
            names = ", ".join(f.name for f in log_files[:3])
            self._data_status.setText(f"Cluster logs found: {names}")
            self._data_status.setStyleSheet("color: #22c55e;")
        else:
            self._data_status.setText("No cluster data found — run Clustered Playlists first.")
            self._data_status.setStyleSheet("color: #f59e0b;")

    def _on_library_changed(self, path: str) -> None:
        self._check_data()
